name: ss_moscow_2020
channels:
  - rdkit
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas
  - matplotlib
# - cudatoolkit=10.2  # use if have GPU (although have not yet made sure the notebook can run on a GPU).
  - ignite
  - ipython
  - jsonschema
  - jupyter
  - jupyterlab
  - pytorch=1.6.0
  - rdkit=2020.03.1.0
  - torchtext
  - torchvision
  - tqdm
  - pip:
    - docopt
    - ipdb
    - tabulate
    - tensorboard
    - scikit-learn
    - pytorch-lightning==0.9.0
    - watermark==2
    - altair==4.1
    - vega==3.4.0

